### ISSUE TITLE
Problem with Blocky changing alarm status.

### ISSUE THREAD

**Issue by szuwix** [Wizzard72/Domoticz-Alarm#11]
Hello.

I'm trying to adapt your script to my device to activate/deactivate the alarm but at any attempt to change the select switch I get an error in the logs : 

Error: EventSystem: Lua script error (Blockly),
Name: wlaczenie alarmu M garaz_1 => [string "result = 0; weekday = os.date('*t')['wday']; ..."]:1: 'then' expected near 'comparevariable'

If I replace the select switch with my dummy select switch, everything is ok.

**Comment by Wizzard72** [comment]
Do I understand it correctly that you try to use a Blocky to switch the device "Arming Mode"? Can you share your Blocky?

I have this working with a dzVents script, so I suppose it should work with Blocky.

**Comment by Wizzard72** [comment]
No new comments for a while. Closing this Issue.
