### ISSUE TITLE
Build in Security panel does not folow the Alarmsysteem - Arming Mode selector switch

### ISSUE THREAD

**Issue by ahattink** [Wizzard72/Domoticz-Alarm#12]
The usage of the Security panel of Domoticz is important for my use.
I hooked up an Keypad, which can change the status of this panel.

The "Alarmsysteem - Arming Mode" selector switch does not follow the status of the panel.
The panel is following the selector switch, though.

So, opening the security panel, type in the code and press Disarm, Arm Home or Arm Away results in not activating of de-activating the Alarm. And therefore the same is applicable when I use my Keypad.

Could this minor issue be resolved?

**Comment by Wizzard72** [comment]
For now it's only one way. What you can do is create a dzVents script that is triggered bij de security panel and when the security panel is turned off it turns off the alarm systemen.

I can put your feature request on my to do list.

**Comment by ahattink** [comment]
Hi Wizzard,

Thanks for your reply and explanation! Please consider this issue a feature request.
In the mean time I will look into dzVents script to change the switch status.

**Comment by Beastie971** [comment]
> For now it's only one way. What you can do is create a dzVents script that is triggered bij de security panel and when the security panel is turned off it turns off the alarm systemen.
> 
> I can put your feature request on my to do list.

Seems to work here. Did you changed the code recently ?

**Comment by Wizzard72** [comment]
No, didn't change any code yet

**Comment by Beastie971** [comment]
Perhaps i can have look on this

**Comment by Wizzard72** [comment]
In the onHeartbeat part we can check the security panel state and if it's changed to disarmed we can disarm the plugin zones.

**Comment by Beastie971** [comment]
yes. I was also thinkingthat there is perhaps another onXXX function called on a device change. But in don't well the plugin

**Comment by Wizzard72** [comment]
I can take a look at this this week

**Comment by Beastie971** [comment]
I think i am just near the solution. Juste a probleme to change de value of "Alarme - Arming Mode (Zone 0)" with UpdateDevice

**Comment by Beastie971** [comment]
Yep. Please be tolerant, i'am not a developer and i am a beginner in python. 
[plugin.py.gz](https://github.com/Wizzard72/Domoticz-Alarm/files/6626293/plugin.py.gz)

**Comment by Wizzard72** [comment]
Thanks for the work! I'm also no developer and learned python while writing my plugins.

**Comment by Beastie971** [comment]
You're  welcome !

**Comment by Wizzard72** [comment]
Merged into Master.

**Comment by ahattink** [comment]
Super work guys! After updating it works like an charm. I am happy!
