### ISSUE TITLE
"Selector Switch" type devices

### ISSUE THREAD

**Issue by Beastie971** [Wizzard72/Domoticz-Alarm#13]
Hi
As i understand the python code, 'Selector switch" devices do not seem to be friendly with the plugin code.
I am doing some changes in it.

**Comment by Wizzard72** [comment]
I don't know what you mean. But happy to apply better code

**Comment by Beastie971** [comment]
Hi 

Some devices can have more than 2 values which can be "Off|Tamper|Alarm|Tamper+Alarm"
#
 
![Capture d’écran du 2021-06-07 18-48-42](https://user-images.githubusercontent.com/83432534/121059018-424ead00-c7c1-11eb-90d8-be0f3cf99382.png)

**Comment by Wizzard72** [comment]
I didn't know that PIR devices could have more options than On/Off. I have 2 different brands and both are On/Off switches. It's possible to check what kind of device it is (normal switch or selector switch). Depending of the type of switch we do different actions.

**Comment by Beastie971** [comment]
I did it in the code. How can share this modification and the one on the security panel ?

**Comment by Wizzard72** [comment]
Can you attach the plugin.py file here?

**Comment by Wizzard72** [comment]
Merged into Master.
