### ISSUE TITLE
Only 1 Zone

### ISSUE THREAD

**Issue by ilkaskim** [Wizzard72/Domoticz-Alarm#19]
Hello, thank you very much for your plugin. I've set everything so far. But I only have one zone and don't need zone 1, for example. Can I just delete it ??

nice greetings
ilkaskim

**Comment by ilkaskim** [comment]
![Screenshot_20211214-225045_Samsung Internet](https://user-images.githubusercontent.com/16821599/146085217-f1ce53f1-a389-4ff5-93ce-6e4e04ecbf8c.jpg)
This is what I set.

**Comment by Wizzard72** [comment]
Delete all devices that the plugin created. Then stop the plugin. Remove both of the ;0 at the 'Sensors in Zone Armed Away' and 'Sensors in Zone Armed Home'. Enable the plugin. Then you have only Zone 0.

**Comment by ilkaskim** [comment]
Thx, I will do it tomorrow.
I have one more question. Can I rename the devices Or does it have any effect on the function of the plugin?

**Comment by Wizzard72** [comment]
The Arming Mode and the Armin Status can't be changed. These are dynamic. The others can be renamed.

**Comment by ilkaskim** [comment]
thanks, everything worked.!
