### ISSUE TITLE
Issue: Rearming the zone doesn't seem to work

### ISSUE THREAD

**Issue by jerkelens** [Wizzard72/Domoticz-Alarm#6]
As per your request, I'll create an issue for the apparent rearming of an already triggered alarm. The zone goes to Off, instead of Normal, hence SIREN doesn't re-trigger if nessecary. In addition, disarming the system and rearming it, does solve the problem, until it is triggered again, then the problem reoccurs.

Like I said, this is on dz2020.2 in the latest plugin version.

**Comment by Wizzard72** [comment]
Should be fixed in version 1.1.1.

Can you test?
