### ISSUE TITLE
Issue: Arming state shouldn't be configurable

### ISSUE THREAD

**Issue by jerkelens** [Wizzard72/Domoticz-Alarm#7]
It feels weird Arming State (per zone) is a manually settable field. If for example I arm the system and an Open Section is detected, I can manully set it "Normal", in which the system appears armed. However, this does not guarantee any kind of integrity of the systems safety state.

**Comment by Wizzard72** [comment]
The Arming State is nog settable field. You can change it, but this value is not stored. You can see that in the log. Also when refreshing the page it's returned to original value
