### ISSUE TITLE
Issue: Sensor Active Time & Open Sections Timeout not saving settings

### ISSUE THREAD

**Issue by jerkelens** [Wizzard72/Domoticz-Alarm#8]
In 1.1.1 you can define settings for the aforementioned timers. Their default is 50 sec., which you can edit through the dropdown menu's. However, these settings aren't saved. If you change the 50 to for example 30, and refresh the page, the setting is reset to 50. This applies to both timers and is reproduceable.

**Comment by Wizzard72** [comment]
Solved in version 1.1.2. Please test.
